### ISSUE TITLE
Custom roles do not appears in reports

### ISSUE THREAD

**Issue by Francoisberthier** [fmido88/moodle-report_completionall#1]
Hello, first of all thank you very much for this very useful plugin. I'm having a little difficulty getting several roles to appear in the activity report. Indeed, despite the fact that the ability “moodle/course:isincompletionreports” is allowed for several of my roles (which therefore appear well in the classic completion reports), my custom roles do not appear in the report generated by the plugin.

Any idea where this might be going wrong? I've looked at the code, but without success...

**Comment by fmido88** [comment]
Thanks @Francoisberthier I spotted the problem and this commit should fix it.

**Comment by Francoisberthier** [comment]
Its works ! Thank you :)
